BULK INSERT dbo.Stanowisko FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\Stanowisko.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.Gatunek FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\Gatunek.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.TypZdarzenia FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\TypZdarzenia.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.Weterynarz FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\Weterynarz.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.Pracownik FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\Pracownik.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.Zwierze FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\Zwierze.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.Wizyta FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\Wizyta.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.Zdarzenie FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\Zdarzenie.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')
BULK INSERT dbo.ZdarzeniePracownik FROM 'E:\!5sem\Hurtowanie Danych\generator\BI_Generator\BI_Generator\bin\Debug\Output\ZdarzeniePracownik.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR = '\n', DATAFILETYPE='widechar')

